networks:
  app-network:
    driver: bridge


services:

  # CAUTION: THE USER SERVICE IS CORRECTLY DEFINED HERE BUT MUTED FOR NOW
#  user:
#    image: user-dev:latest
#    build:
#      context: ./user-microservice
#      dockerfile: ./Dockerfile
#      target: dev
#    tty: true
#    container_name: user_backend
#    restart: always
#    volumes:
#      - "./user-microservice/src/:/src"
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - app-network
#    ports:
#      - "8080:8080"
#      - "50050:50050"

#  quartz:
#    image: quartz-dev:latest
#    build:
#      context: ./quartz-microservice
#      dockerfile: ./Dockerfile
#      target: dev
#    tty: true
#    container_name: quartz_backend
#    restart: always
#    volumes:
#      - "./quartz-microservice/src/:/src"

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/data/data
    tty: true
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: application
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d application"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - .data/kafka:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: CONTROLLER://kafka:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    restart: always
    networks:
      - app-network

